// Default Role Permissions - Initial configuration
import { ROLES, type Role } from "@/lib/auth/roles";
import { PERMISSIONS, type Permission } from "./constants";

// Default permissions for each role
export const DEFAULT_ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.SUPER_ADMIN]: [], // All permissions (handled in code)
  [ROLES.ADMIN]: [], // All permissions (handled in code)
  
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.CLASSES_VIEW,
    PERMISSIONS.SECTIONS_VIEW,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.FEES_STRUCTURE,
    PERMISSIONS.FEES_DISCOUNT,
    PERMISSIONS.FEES_REPORTS,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_FINANCIAL,
    PERMISSIONS.REPORTS_EXPORT,
  ],
  
  [ROLES.TEACHER]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.CLASSES_VIEW,
    PERMISSIONS.SECTIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  
  [ROLES.OPERATOR]: [
    PERMISSIONS.STUDENTS_VIEW,
    PERMISSIONS.STUDENTS_CREATE,
    PERMISSIONS.STUDENTS_EDIT,
    PERMISSIONS.CLASSES_VIEW,
    PERMISSIONS.CLASSES_CREATE,
    PERMISSIONS.CLASSES_EDIT,
    PERMISSIONS.SECTIONS_VIEW,
    PERMISSIONS.SECTIONS_CREATE,
    PERMISSIONS.SECTIONS_EDIT,
    PERMISSIONS.TEACHERS_VIEW,
    PERMISSIONS.TEACHERS_CREATE,
    PERMISSIONS.TEACHERS_EDIT,
    PERMISSIONS.FEES_VIEW,
    PERMISSIONS.FEES_COLLECT,
    PERMISSIONS.CERTIFICATES_VIEW,
    PERMISSIONS.CERTIFICATES_GENERATE,
  ],
  
  [ROLES.STUDENT]: [
    // Students can only view their own data (enforced by RLS)
  ],
  
  [ROLES.PARENT]: [
    // Parents can only view their children's data (enforced by RLS)
  ],
};
